name: Deploy service to Google Cloud Run

on: [push]

jobs:
  deploy: 
    name: Deploy to Google Cloud
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    # checkout to the working branch
      - name: Checkout
        uses: actions/checkout@v3

    # Setup gcloud CLI
      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
      - run: |-
         gcloud --quiet auth configure-docker

      - name: Build and Push Container
        run: |-
          docker build -t gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.SERVICE }}:${{  github.sha }} .
          docker push gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.SERVICE }}:${{  github.sha }}

      - name: Deploy to Google Cloud Run
        uses: 'google-github-actions/deploy-cloudrun@v0'
        with:
          service: '${{ secrets.SERVICE }}'
          image: 'gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.SERVICE }}:${{  github.sha }}'
          region: '${{ secrets.REGION }}'
          env_vars: |
            ERGAST_API_RESPONSE_TYPE=${{ secrets.ERGAST_API_RESPONSE_TYPE }}
            ERGAST_API_ENDPOINT=${{ secrets.ERGAST_API_ENDPOINT }}
